### PR TITLE
fix: toaster vanishing to quickly when saving a slice

### PR DESCRIPTION
**Pull request by MarcMcIntosh**
## Context
Toast was disappearing when saving a slice because it was being unmounted. move the ToastConainer further up in the component tree seems to have solved the issue.|

https://linear.app/prismic/issue/DT-1531/[spike-1-day]-slice-creation-notification-disappears-too-fast

## Checklist before requesting a review
- [x] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

### CODE REVIEW

**Comment by xrutayisire** [comment]
Hum @MarcMcIntosh I still have the issue on my side on your branch :/


https://github.com/prismicio/slice-machine/assets/19946868/0ba34d93-5b72-46b3-b46a-c021013a7622

**Comment by MarcMcIntosh** [comment]
@xrutayisire really I just checkout it out, refreshed and tried again and it worked :/

**Comment by MarcMcIntosh** [comment]
Ahh this is happening when creating a slice

**Comment by xrutayisire** [comment]
> Ahh this is happening when creating a slice

Yes, and sometimes only the second slice that I create :/

**Comment by xrutayisire** [comment]
Couldn't reproduce anymore, so LGTM 👍

**Review by xrutayisire — APPROVED** [review]

**Pull request merged**
