### PR TITLE
fix(adapter-next): improve usability of snippets

### PR DESCRIPTION
**Pull request by angeloashmore**
**Resolves**: A request by @a-trost

### Description

This PR updates `@slicemachine/adapter-next`'s snippets. The updated snippets better reflect how developers render and use the data.

#### Group snippet

The previous snippet included a fragment (`<></>`) and did not use an implicit return (`() => ()`), requiring users to modify the snippet before using it. It was written that way for Prettier compatibility, but a snippet that works immediately is better than one that requires editing by a user.

> **Old**:
> 
> ```tsx
> <>
>   {slice.primary.my_group.map((item) => {
>     // Render the item
>   })}
> </>
> ```
> 
> **New**:
> 
> ```tsx
> {slice.primary.my_group.map((item) => (
>   // Render the item
> ))}
> ```

#### Other snippets

The wrapping `<></>` fragments were removed. They were originally added to support Prettier formatting, but the snippets are simple enough to not need automatic formatting.

> **Old**:
> 
> ```tsx
> <>{slice.primary.my_key_text}</>
> ```
> 
> **New**:
> 
> ```tsx
> {slice.primary.my_key_text}
> ```

### Checklist

- [x] If my changes require tests, I added them.
- [ ] If my changes affect backward compatibility, it has been discussed.
- [ ] If my changes require an update to the CONTRIBUTING.md guide, I updated it.

### Preview

image

### How to QA [^1]

1. Start a new playground with `yarn dev` + `yarn play --new`.
2. In Slice Machine, add a group to an existing custom type.
3. View the code snippet.

🐤

[^1]:
    Please use these labels when submitting a review:
    :question: #ask:&ensp;Ask a question.
    :bulb: #idea:&ensp;Suggest an idea.
    :warning: #issue:&ensp;Strongly suggest a change.
    :tada: #nice:&ensp;Share a compliment.

### CODE REVIEW

**Comment by a-trost** [comment]
Thanks so much for changing this! Definitely more immediately usable this way.

**Review by dani-mp — APPROVED** [review]

**Review by xrutayisire — COMMENTED** [review]
It's the same for all the others snippets that include a fragment, right?

It could be improved to prevent having a fragment so the copy-paste works without user having to remove the fragment. Or for you, it's not better for the others snippets?

**Comment by angeloashmore** [comment]
@xrutayisire Good point! We can remove fragments from all snippets that have them using the same reasoning.

**Review by xrutayisire — APPROVED** [review]
Nice work!

**Pull request merged**
