### PR TITLE
AAU, when I have pushed at least 1 slice and 1 custom type, I see a modal asking for my review on the SM

### PR DESCRIPTION
**Pull request by Miniplop**
## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. (PR: #)
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by arnaudlewis** [comment]
So we plan on keeping the localStorage for v1 or is it just an in-between solution just to get something running first?

**Comment by Miniplop** [comment]
Modal without the comment

image

Modal wit the comment

image

**Comment by Miniplop** [comment]
> So we plan on keeping the localStorage for v1 or is it just an in-between solution just to get something running first?

Yes we will keep this for the V1, and dig into more complex solutions as soon as the tracking feature became bigger

cc @arnaudlewis

**Comment by arnaudlewis** [comment]
Ok ;)

Le lun. 11 oct. 2021 à 12:20, Kevin Jean ***@***.***> a
écrit :

**Comment by Miniplop** [comment]
Don 't merge this PR for now, we must change the endpoint by the tracking url in prod

**Pull request merged**
