### PR TITLE
feat(adapter-sveltekit): add `@slicemachine/adapter-sveltekit`

### PR DESCRIPTION
**Pull request by angeloashmore**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR adds `@slicemachine/adapter-sveltekit`.

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

🦆

### CODE REVIEW

**Comment by bapmrl** [comment]
Excellent! Thanks for taking time to go through all my comments. I can now make the simulator work, but I got the following console error:
Screenshot 2023-08-25 at 16 24 08
```
��error��name�TypeError�message�8Invalid version. Must be a string. Got type "undefined".�stack�"TypeError: Invalid version. Must be a string. Got type "undefined".
    at new SemVer (/Users/bapmrl/Code/slice-machine/node_modules/semver/classes/semver.js:19:13)
    at compare (/Users/bapmrl/Code/slice-machine/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/Users/bapmrl/Code/slice-machine/node_modules/semver/functions/gt.js:2:29)
    at VersionsManager.checkIsAdapterUpdateAvailable (/Users/bapmrl/Code/slice-machine/packages/manager/dist/managers/versions/VersionsManager.cjs:127:19)
    at async Module.handleRPCRequest (/Users/bapmrl/Code/slice-machine/packages/manager/dist/_node_modules/r19/dist/handleRPCRequest.cjs:58:11)
    at async IncomingMessage.<anonymous> (/Users/bapmrl/Code/slice-machine/packages/manager/dist/_node_modules/r19/dist/createRPCMiddleware.cjs:17:45)
```

**Review by bapmrl — APPROVED** [review]
Approved!

**Comment by angeloashmore** [comment]
> @bapmrl: I can now make the simulator work, but I got the following console error…

The error comes from `manager.versions.checkIsAdapterUpdateAvailable()`. Since `@slicemachine/adapter-sveltekit` does not have any stable versions published (v0.0.0 does not qualify), the `semver.gt()` is provided an invalid `undefined` value.

This error will be resolved once we publish a stable version of `@slicemachine/adapter-sveltekit`.

Could we open a separate ticket for that bug and handle it outside the adapter PR?

**Comment by bapmrl** [comment]
> > @bapmrl: I can now make the simulator work, but I got the following console error…
> 
> The error comes from `manager.versions.checkIsAdapterUpdateAvailable()`. Since `@slicemachine/adapter-sveltekit` does not have any stable versions published (v0.0.0 does not qualify), the `semver.gt()` is provided an invalid `undefined` value.
> 
> This error will be resolved once we publish a stable version of `@slicemachine/adapter-sveltekit`.
> 
> Could we open a separate ticket for that bug and handle it outside the adapter PR?

No problem! Thanks @angeloashmore 🙂

CC @xrutayisire and @hypervillain.

**Comment by xrutayisire** [comment]
> Could we open a separate ticket for that bug and handle it outside the adapter PR?

Hum, so for me, we should release a 0.1.0 when we make the adapter public, right?
Then I guess we don't really need a ticket since it will work. WDYT @angeloashmore ?

Screenshot 2023-08-28 at 18 59 05

**Comment by angeloashmore** [comment]
@xrutayisire Yes, we should release `@slicemachine/adapter-sveltekit` as something equivalent to ^0.1.0.

It's true that the bug won't happen once the adapter is released, but it could still be good to patch `manager.versions.checkIsAdapterUpdateAvailable()` to not throw when no stable versions can be found. It could be as simple as:

```sh
if (stableVersions.length < 1) {
  return false;
}
```

This is certainly not a priority issue, just some housecleaning. 🙂

**Pull request merged**
