### PR TITLE
refactor(black-slate): add spacious variation

### PR DESCRIPTION
**Pull request by MarcMcIntosh**
## Context
[Ticket](https://linear.app/prismic/issue/DT-1524/aadev-i-need-to-add-a-spacious-option-to-the-blankslate-component)

Adds a spacious variation to the blank slate component, this sets the width and height to 100%
completes DT-1524

Screenshot 2023-08-04 at 13 29 50

## Checklist before requesting a review
- [ ] I hereby declare my code ready for review.
- [ ] If it is a critical feature, I have added tests.
- [ ] The CI is successful.
- [ ] If there could backward compatibility issues, it has been discussed and planned.

### CODE REVIEW

**Comment by xrutayisire** [comment]
I'm not sure to get this issue and maybe you can help me.

When I read:
> This already has been implemented by @xavier.rutayisire, but I wonder if we could simplify the API by simply having to pass a variant or boolean to control how the BlankSlateImage is displayed — instead of having a redundant backgroundImage prop.

I feel like the goal is to remove the backgroundImage prop on the main component and instead keep using BlankSlateImage but by setting a variant spacious it would put the image in full width like visually it is today with my code.

@bapmrl maybe you could confirm or not 🙂

**Comment by MarcMcIntosh** [comment]
@xrutayisire we discussed the options for removing the background prop during the daily and we decided that it would be simpler to keep it rather than iterating over the children to maybe find an image child, and take the image prop from that :)

**Comment by xrutayisire** [comment]
Ok thanks @MarcMcIntosh.

I don't really understand the code:
- large is a variation?
- what's the difference visually between the two stories "Background" and "Spacious"
- what is the use case the change is for?

I feel like the code is a bit harder to understand now, with hasBackground, spacious, large, variation. Maybe I'm missing something.
If needed, we can call to sync 🙂

**Comment by MarcMcIntosh** [comment]
Sure a call would be best :)

**Comment by bapmrl** [comment]
Continued in https://github.com/prismicio/slice-machine/pull/1105. Thanks a lot Marc 😊

**Pull request closed without merging**
