### PR TITLE
fix(slice-machine-ui): layout shift

### LINKED ISSUE #1097: Avoid Layout shift from the main layout grid scrollbar
Just a minor request to add the CSS `scrollbar-gutter: stable;` property on the main layout grid to avoid a layout shift when you go from pages with a scrollbar to scrollbarless pages. This is really visible since the 1.8.0 version.

### PR DESCRIPTION
**Pull request by bapmrl**
Completes DT-1549 and resolves #1097.

Please note that users may still experience layout shifts when using the custom type or slice builder. We'll need to redesign these pages when we can.

### CODE REVIEW

**Comment by xrutayisire** [comment]
I still see the layout shift on my side 😕


https://github.com/prismicio/slice-machine/assets/19946868/e5daf254-e8fd-4d82-a21e-e2b0a842b2a9

**Comment by xrutayisire** [comment]
The table design changed, I guess it's not wanted:

Before:
Screenshot 2023-08-17 at 11 06 38

After:
Screenshot 2023-08-17 at 11 06 55

**Comment by bapmrl** [comment]
I've fixed the row height and will check the behaviour on Arc 🙂

**Comment by bapmrl** [comment]
I could not reproduce the same behaviour on Arc 😢

**Review by xrutayisire — APPROVED** [review]
LGTM 👍

**Pull request merged**
