### PR TITLE
[DT-2245] feat: display static and slice zone right away

### PR DESCRIPTION
**Pull request by BohdanOne**
**Resolves**: [DT-2245](https://linear.app/prismic/issue/DT-2245/replace-the-initial-empty-page-type-screen)

### Description

Simplify the onboarding by removing the difference in page type builder page that occurs on adding new page.
This is not completed feature! In next steps placeholder for empty Static Zone will be removed.

### Checklist

- [ ] If my changes require tests, I added them.
- [ ] If my changes affect backward compatibility, it has been discussed.
- [ ] If my changes require an update to the CONTRIBUTING.md guide, I updated it.

### Preview
**BEFORE**
new-page-before
**AFTER**
new-page-after

### How to QA [^1]

[^1]:
	Please use these labels when submitting a review:
	:question: #ask:&ensp;Ask a question.
	:bulb: #idea:&ensp;Suggest an idea.
	:warning: #issue:&ensp;Strongly suggest a change.
	:tada: #nice:&ensp;Share a compliment.

### CODE REVIEW

**Review by levimykel — DISMISSED** [review]
Looks good to me 😄

**Review by levimykel — COMMENTED** [review]
In `SliceZone`, is `redirectToEditMode` still needed? And thus, is `useRouter` still needed?

**Comment by BohdanOne** [comment]
> In `SliceZone`, is `redirectToEditMode` still needed? And thus, is `useRouter` still needed?

not sure, was focused only on UI changes, but it's possible you're right, will double-check that!

**Review by xrutayisire — CHANGES_REQUESTED** [review]
⚠️ #issue

I don't understand this implementation here. Are we not supposed to remove the placeholder to push devs to add slices and not see the huge placeholder to create fields?

Screenshot 2024-08-08 at 09 34 34

**Comment by BohdanOne** [comment]
> ⚠️ #issue
> 
> I don't understand this implementation here. Are we not supposed to remove the placeholder to push devs to add slices and not see the huge placeholder to create fields?
> 
@xrutayisire 
Yes, that is next step, in order to do that we need to move 'add fields' button. 
So this is just the first step, more to follow today (my bad, I could state that in pr description).

**Review by xrutayisire — COMMENTED** [review]
Ok nice 👌 No problem I didn't know, that's also the goal of PR 💪

**Comment by xrutayisire** [comment]
I let Levi approve as I didn't check the code on my side 🙂

**Review by levimykel — APPROVED** [review]
Looks good to me, nice work 😄

**Pull request merged**
